global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'jmeter'
    static_configs:
      - targets: ['host.docker.internal:9270']
  - job_name: 'jfr-metrics-app'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Use host.docker.internal:8080 if running in Docker
    metrics_path: /actuator/prometheus  # Use /metrics for standalone Java app